### ISSUE TITLE
[BUG] 1.19 worker 500s at boot on Next.js 16 ("ComponentMod.handler is not a function" / "reading 'require'"); works on 1.14.7

### ISSUE THREAD

**Issue by jakebromberg** [opennextjs/opennextjs-cloudflare#1286]
## Summary

Upgrading `@opennextjs/cloudflare` from **1.14.7 → 1.19.11** makes the deployed Cloudflare Pages worker return **HTTP 500 at boot** for a Next.js 16 app. The exact same app/config boots and serves 200 on 1.14.7. The crash is at worker module-init (before app code runs), so the build and deploy stages both succeed — only a runtime probe of `/` reveals it. Errors below were captured from the live edge via `wrangler pages deployment tail`.

## Two distinct failure modes

**1. Default Next 16 build (Turbopack is the default bundler for `next build` in Next 16):**

```
⨯ Error: Failed to load external module next/dist/compiled/next-server/app-page-turbo.runtime.prod.js: TypeError: Cannot read properties of undefined (reading 'require')
⨯ TypeError: components.ComponentMod.handler is not a function
```

The external-module loader can't load Next 16's Turbopack-compiled `app-page-turbo.runtime.prod.js`, so the page handler is never bound (hence the downstream `ComponentMod.handler is not a function`).

**2. After switching the build to webpack (`next build --webpack`):**

I verified the OpenNext bundle then resolves the non-turbo `app-page.runtime.prod.js` (zero `app-page-turbo` references in the emitted server bundle). The Turbopack load failure and the `ComponentMod.handler` error are both gone — but the worker **still 500s at boot** with a residual, bundler-independent:

```
⨯ TypeError: Cannot read properties of undefined (reading 'require')
```

So there appear to be (at least) two separate 1.19 edge-boot regressions: the Turbopack-runtime load failure sits on top of a deeper `require`-on-undefined at module-init that persists even with a webpack build.

## Works on 1.14.7

Same app, same `open-next.config.ts`, same `wrangler.jsonc` (`compatibility_date: 2025-10-11`, `nodejs_compat_v2`), `output: "standalone"` — boots and serves 200 on `@opennextjs/cloudflare` **1.14.7**. So this is a regression somewhere between 1.14.7 and 1.19.11. (Switching the flag to `nodejs_compat` made no difference — ruled out.)

## Environment

- `@opennextjs/cloudflare`: **1.19.11** (regression vs **1.14.7**, which works)
- `next`: 16.2.9
- `wrangler`: 4.103.0 (also reproduced on 4.95.0 — not the variable)
- Cloudflare Pages; `compatibility_date = 2025-10-11`; `compatibility_flags = ["nodejs_compat_v2", "global_fetch_strictly_public"]`
- `next.config`: `output: "standalone"`
- `open-next.config.ts` (abridged): `wrapper: "cloudflare-node"`, `converter: "edge"`, dummy `incrementalCache`/`tagCache`/`queue`, `edgeExternals: ["node:crypto"]`, `middleware: { external: true, wrapper: "cloudflare-edge", converter: "edge" }`

## Repro

1. A Next.js 16 app with `output: "standalone"`, built via the OpenNext Cloudflare standalone build (`opennextjs-cloudflare build`).
2. Deploy to a Cloudflare Pages preview.
3. `GET /` → HTTP 500; `wrangler pages deployment tail <deployment-id>` shows the errors above.

Happy to provide a minimal reproduction or test intermediate versions to help bisect the regression — just let me know what would be most useful.

**Comment by conico974** [comment]
@jakebromberg Please provide a minimum reproduction

**Comment by jakebromberg** [comment]
Spent a while trying to produce a minimal reproduction and have **not** been able to reproduce the boot 500 — sharing the full investigation, since the negative result is itself informative.

**TL;DR:** I can't reproduce `Cannot read properties of undefined (reading 'require')` / `ComponentMod.handler is not a function` from a clean build of either a minimal app or my real app on `@opennextjs/cloudflare@1.19.11` + Next 16.2.x. Every clean build with `nodejs_compat_v2` + a recent `compatibility_date` serves 200 on real Pages edge. The failure looks specific to the deploy *environment*, not the code or the adapter version.

### What I tested

All deployed to a real Pages project (`_worker.js` advanced mode), `compatibility_flags: ["nodejs_compat_v2"]`, `compatibility_date: "2025-10-11"`:

| Bundle | Build env | Next | Result |
|---|---|---|---|
| Minimal app | macOS | 16.2.9 | ✅ 200 |
| Minimal app + `node:crypto` middleware | macOS | 16.2.9 | ✅ 200 |
| Full real app | macOS | 16.2.9 | ✅ 200 |
| Full real app | Linux / Node 24 (matches the Pages build image) | 16.2.9 | ✅ 200 |
| Full real app | Linux / Node 24 | 16.2.6 (peer floor) | ✅ 200 |

Compat controls (same Linux bundle):

- No `nodejs_compat*` flag → **522** (isolate never instantiates; `node:async_hooks` / `node:process` / `node:buffer` unresolved).
- `nodejs_compat` + a pre-`2024-09-23` `compatibility_date` (v1 semantics) → **522** (also won't start).

That 522-vs-500 distinction is the key data point: with broken compat the worker doesn't start *at all*, which is not this bug. The reported error happens *after* the worker has started — it gets into the app-page render and the external-module loader for `app-page-turbo.runtime.prod.js` throws. None of the compat permutations land in that middle state.

### Stale-cache hypothesis — tested, not confirmed

Since `1.14.7 → 1.19.11` is a major bump and Pages reuses build caches, I built a deliberately version-mismatched bundle: the 16.2.9 worker + Turbopack runtime, but with the **16.1.6** `app-page-turbo.runtime.prod.js` swapped into `node_modules` and re-inlined via `opennextjs-cloudflare build --skipBuild`. It also served **200**. So a single mismatched external-runtime file is not enough to trigger this on its own.

### Three things worth noting regardless

1. `1.19.11` peer-requires `next@">=15.5.18 <16 || >=16.2.6"` — it drops 16.0–16.2.5. So a "1.14.7 vs 1.19.11" comparison can't hold Next constant; bumping the adapter forces Next off 16.0–16.2.5.
2. `1.14.7` can't build Next 16.2 at all — it crashes at runtime with `Unexpected loadManifest(/.next/server/prefetch-hints.json)`. So the known-good "1.14.7" path is really 1.14.7 + Next ≤ 16.1.x, i.e. a different Next runtime than 1.19.11 loads.
3. Repro gotcha for anyone trying this via Docker on macOS: building OpenNext on a Docker-Desktop bind-mounted volume gives a *false* `esbuild: Could not resolve "./open-next.config.mjs"`. Building in the container's native filesystem fixes it.

Given it reproduces nowhere I can construct it cleanly, my working assumption is this is deployment-environment-specific (Pages Git-build state). I'll follow up with the full Cloudflare build log + the `wrangler` / dashboard compat settings from the actual failing deployment. If there's a specific artifact you'd want captured from a failing build, tell me what and I'll grab it.

**Comment by jakebromberg** [comment]
**Resolved — root cause is the `wrangler` version Cloudflare Pages uses to compile the worker, not the app, the bundler, or the OpenNext version.**

Pulled the build log for my failing Pages deployment (as promised) and isolated it to a single variable. The OpenNext bundle itself is fine — the failure comes from the **final `_worker.js` compile/upload step**, which **Cloudflare Pages *Git builds* run with their own pinned `wrangler 3.114.17`**, regardless of the `wrangler` version in `package.json`. It's right there at the end of the Pages build log:

```
Found _worker.js in output directory. Uploading.
 ⛅️ wrangler 3.114.17
✨ Compiled Worker successfully
```

### Isolation

I took one single `.open-next` bundle and changed *only* the wrangler version that runs `pages deploy` on it:

| wrangler that compiles/uploads `_worker.js` | runtime |
|---|---|
| `3.114.17` (Pages Git-build default) | ❌ 500 — `TypeError: Cannot read properties of undefined (reading 'require')` + `components.ComponentMod.handler is not a function` |
| `4.0.0` … `4.32.0` | ❌ 500 (same) |
| **`4.33.2`** and later (incl. `4.90.1`) | ✅ 200 |

So it's a wrangler compile regression spanning **3.x through 4.32, fixed in 4.33**. Errors captured live with `wrangler pages deployment tail`; both reported errors reproduce.

### Minimal repro

```bash
# any OpenNext 1.19.x app, after `opennextjs-cloudflare build`
npx wrangler@3.114.17 pages deploy .open-next/assets   # -> boot 500 (reading 'require')
npx wrangler@4.90.1   pages deploy .open-next/assets   # same bundle -> 200
```

### Why the usual suspects were red herrings

Turbopack vs `next build --webpack`, the Next 16.2.x patch (16.2.6 / 16.2.9), build OS/Node, and `nodejs_compat` flags made **no** difference — every one of those served 200 when compiled by wrangler ≥ 4.33 and 500 when compiled by ≤ 4.32. It's also consistent with "works on 1.14.7": that release's worker doesn't go through the external-module `require` path the old wrangler miscompiles.

### Workarounds

- Deploy via **Direct Upload with a current wrangler** (`opennextjs-cloudflare build` then `wrangler@>=4.33 pages deploy .open-next/assets`) from your own CI, instead of the Pages Git integration.
- Or deploy to **Workers** instead of Pages, which builds with your project's own wrangler.

The real fix is on Cloudflare's side — the Pages Git-build pipeline pins a wrangler (`3.114.17`) far older than the `4.33` that fixed this. I'll open a Cloudflare Pages issue referencing this. Happy to share the full build log or a minimal repo.

**Comment by james-elicx** [comment]
OpenNext is for Cloudflare Workers. It will not work properly, if at all, on Cloudflare Pages.

Please use `opennextjs-cloudflare deploy`, `opennextjs-cloudflare upload`, `wrangler deploy`, or `wrangler version upload` instead of `wrangler pages deploy`.

https://opennext.js.org/cloudflare/howtos/dev-deploy#deploy-your-application-to-cloudflare-workers

**Comment by MattieTK** [comment]
@jakebromberg can you share which LLM and harness produced this?
